trigger:
  branches:
    include:
      - main

steps:  

- task: AzureCLI@2
  displayName: 'Deploy static site with AzCopy'
  inputs:
    azureSubscription: 'EDD-General-Prod'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -euo pipefail

      STORAGE_ACCOUNT_NAME="uxguide2"
      SOURCE_FOLDER="."

      echo "Enabling static website..."
      az storage blob service-properties update \
        --account-name "$STORAGE_ACCOUNT_NAME" \
        --auth-mode login \
        --static-website \
        --index-document index.html \
        --404-document 404.html

      echo "Syncing site with AzCopy..."
      az storage blob sync \
        --account-name "$STORAGE_ACCOUNT_NAME" \
        --container '$web' \
        --source "$SOURCE_FOLDER" \
        --auth-mode login \
        --exclude-pattern "*.json;node_modules/*;azure-pipelines/*;.gitignore"



      echo "✅ Upload complete."
